---
- name: transfer monit-config configuration
  template: src={{ item }} dest=/etc/monit/conf.d/{{ item | basename }} mode=0777
  with_fileglob:
    - ../templates/monit-config/*.*
  tags:
    - monit
    - monit-config

