---

- name:
  shell: gem update --system
  become: yes

- homebrew: name={{ item }} state=present
  ignore_errors: true
  with_items:
  - wget
  - htop
  - docker-machine
  - docker-compose
  - zsh
  - zsh-completions
  - git
  - golang
  - htop
  - vim
  - curl
  - multitail
  - node



- homebrew_cask: name={{ item }} state=present
  ignore_errors: true
  with_items:
  - google-chrome
  - slack
  - docker
  - cheatsheet
  - virtualbox
  - 1password
  - cheatsheet
