---
#- xcversion: state=present version=7.1.1
#- xcversion: state=selected version=7.1.1


- gem: name={{ item }} state=present
  ignore_errors: true
  with_items:
    - fastlane
    - cocoapods
    - snapshots

- homebrew: name={{ item }} state=present
  ignore_errors: true
  with_items:
    - swiftlint





